### ISSUE TITLE
termed (gumbobr0t)

### ISSUE THREAD

**Issue by gumbobr0t** [Minecraftkillir/Russian-Roulette.exe#1]
@Minecraftkillir got termed again not gonna make a new discord

**Comment by gumbobr0t** [comment]
but we can chat on telegram

**Comment by Minecraftkillir** [comment]
Yea , I also got termed , was my fav acc , fuck you for that btw , ill send my telegram acc in a sec

**Comment by Minecraftkillir** [comment]
Yea , my number is on telegram is 27605869421

**Comment by gumbobr0t** [comment]
join the rose group so i can message you then privately idk how to add/search for someone by their number

**Comment by gumbobr0t** [comment]
its linked on the rose readme at the top
